version: '3'

services:
    scrapyd:
        image: vimagick/scrapyd
        ports:
            - "6800:6800"
        volumes:
            - ./data:/var/lib/scrapyd
            - /usr/local/lib/python2.7/dist-packages
        restart: always
        depends_on:
            - db
        links:
            - "db:mongo"

    db:
        image: mongo:3.4
        ports:
            - 27017:27017
